# Generated by Django 4.0.4 on 2022-05-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('ID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('university', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('statues', models.CharField(max_length=10)),
                ('course1', models.CharField(max_length=50, null=True)),
                ('course2', models.CharField(max_length=50, null=True)),
                ('course3', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('CourseID', models.IntegerField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=50)),
                ('HallNo', models.CharField(max_length=50)),
                ('Hourses', models.CharField(max_length=50)),
                ('CourseDay', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('registercourse', models.ManyToManyField(to='pages.student')),
            ],
        ),
    ]
