# Generated by Django 4.0.4 on 2022-05-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_courses_courseid_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='CourseID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
